# -*- coding: utf-8 -*-
"""Botellas de  colores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17U0O8-K-4SPzI1pIY0TAJlozw5_v6Aaf
"""

import random
from copy import copy

def botellas_correctas(superior: list[str], inferior: list[str]) -> int:
    coincidencias = 0
    for indices, elementoi in enumerate(superior):
      for indicei, elementoii in enumerate(inferior):
        if (indicei == indices) and (elementoi == elementoii):
          coincidencias += 1
    return coincidencias

def generar_botellas(n: int) -> tuple[list[str], list[str]]:
    # No se puede mas de 20 colores
    assert 0 < n <= 20, "n debe ser entre 1 y 20"
    # Lista de 20 colores diferentes
    colores = ['rojo', 'verde', 'azul', 'amarillo', 'naranja', 'morado', 'rosa', 'negro', 'blanco', 'gris', 'celeste', 'lila', 'turquesa', 'dorado', 'plateado', 'cian', 'magenta', 'marfil', 'beige', 'coral']
    superior = random.sample(colores, k=n)
    inferior = copy(superior)
    # Superior e inferior no pueden ser iguales
    while botellas_correctas(superior, inferior) != 0:
        random.shuffle(inferior)
    return superior, inferior

def swap (lista, i, j):
  objeto1 = lista[i]
  lista[i] = lista[j]
  lista[j] = objeto1

def juego_botellas(n:int):
  resultado = generar_botellas(n)
  lista1 = resultado[0]
  lista2 = resultado[1]
  print(lista1)
  def loop ():
    if botellas_correctas(lista1, lista2) == len(lista1):
      print("Todas las botellas estan en los lugares correctos, GANASTE.")
    else:
      swap(lista1, int(input("Posicion de la primera botella que desea intercambiar: "))-1, int(input("Posicion de la segunda botella que desea intercambiar: "))-1)
      print(lista1)
      print("Correctas: " + str(botellas_correctas(lista1, lista2)))
      loop()
  loop()
  n:int = int(input("Con cuantas botellas desea jugar?"))
  assert 0 < n <= 20, f"El numero de botellas debe ser entre 1 y 20, el numero ingresado es{n}"
  juego_botellas(n)